name: Android Reinstall and Reboot

on:
  repository_dispatch:
    types: [emulator_restart_and_install]

jobs:
  reboot-and-install:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: APK調達
        run: |
          mkdir -p ./app
          curl -L "${{ github.event.client_payload.apk_url }}" -o "./app/${{ github.event.client_payload.file_name }}"
      
      - name: エミュレータ起動 ＆ Python司令実行
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          target: google_apis
          arch: x86_64
          # 🔴 ここに待機設定を強化！
          force-avd-creation: false
          disable-animations: true
          script: |
            # adbがデバイスを認識するまで待機するログを出す
            echo "Waiting for device to be online..."
            adb wait-for-device
            python3 install.py "${{ github.event.client_payload.file_name }}"
        env:
          GAS_URL: "https://script.google.com/macros/s/AKfycbwiAbp9V-hbMmDg_cdn3vlctQgCu6WCVyabBsWprDIBWg9GPzky5Po-ld0Q7bQFXVSmsA/exec" # 🔴要設定
